webform_content_creator.webform_content_creator.*:
  type: config_entity
  label: 'Webform Content Creator config'
  mapping:
    id:
      type: string
      label: 'ID'
    title:
      type: string
      label: 'Title'
    webform:
      type: string
      label: 'Webform'      
    content_type:
      type: string
      label: 'Content type'
    field_title:
      type: string
      label: 'Title'
    use_encrypt:
      type: boolean
      label: 'Use encryption'
    encryption_profile:
      type: string
      label: 'Encryption profile'
    sync_content:
      type: boolean
      label: 'Synchronize content in edition'
    sync_content_delete:
      type: boolean
      label: 'Synchronize content in deletion'
    sync_content_node_field:
      type: string
      label: 'Synchronization field machine name'   
    elements:
      type: sequence
      label: 'Element'
      sequence:
        type: mapping
        mapping:
          type:
            type: boolean
            label: 'Type'
          content_type:
            type: string
            label: 'Content type'
          webform_field:
            type: string
            label: 'Webform field'
          custom_check:
            type: boolean
            label: 'Custom check'
          custom_value:
            type: string
            label: 'Custom value'